### ISSUE TITLE
When I click on "Buy" button, I end up on the Nosoft landing page

### ISSUE THREAD

**Issue by ghost** [TheSimplicityArchitect/NoSoft-Feedbacks#3]
Impossible to pay my app. When I click on "Buy" I end up on the landing page of Nosoft website

**Comment by TheSimplicityArchitect** [comment]
Hi gusmal,
Recently, our website has been updated and some links have been broken :-(
I have updated the addresses in NoSoft and now it should be OK.
Thanks for reporting this bug and as a reward, we decided to offer you an AppCoin !

**Comment by TheSimplicityArchitect** [comment]
Release tests confirmed that this has been fixed
